### ISSUE TITLE
Internationalization and accented characters

### ISSUE THREAD

**Issue by wildunne** [svenkubiak/mangooio#266] opened 2017-03-11 14:22 UTC
I'm using Freemarker templates and the i18n functionality, but
there is an issue whenever using French characters (and 
presumably others that I have not tested).

Given the file which looks like this:
`ctedivoire=Côte d'Ivoire`

It is being rendered in html as:
`CÃ´te d'Ivoire`

Currently this is a non issue, as I don't want the website to 
initially be available in French and I don't think people from
Cote d'Ivoire will mind losing their accent, but it does limit 
it's usefulness. I've tested this when using the `FR` locale
also and the issue still occurs, but I won't rule out me missing
something silly.

**Comment by svenkubiak** [comment] 2017-03-12 14:03
Interessent that the ' does work, because ot is used for escaping.

Can you check what encoding you files have. I will look into it nevertheless.

**Comment by wildunne** [comment] 2017-03-12 14:30
UTF-8, according to intellij

**Comment by svenkubiak** [comment] 2017-03-13 09:39
I have just created new unit tests for special characters and umlaute, including a test on your key. All test work fine. However the ' gets encoded, but this is also as intended.

How did you name your properties file and which OS are you using?

**Comment by wildunne** [comment] 2017-03-13 09:49
Ubuntu in this case. The file is messages_en.properties and 
messages_fr.properties. It's called by ${i18n(variable)}, and 
in this case the variable has a value of ctedivoire

**Comment by svenkubiak** [comment] 2017-03-13 09:55
Please double check correct encoding, as I expect this 99.9% to be an endocing problem:
http://www.i18nqa.com/debug/utf8-debug.html

**Comment by svenkubiak** [comment] 2017-03-21 19:28
Any update on this? Otherwise I would close this for now.

**Closed** 2017-04-07 18:35 UTC
Labels: question
