### ISSUE TITLE
Online documentation has a couple of slips on filter description pages

### ISSUE THREAD

**Issue by ismagilov** [svenkubiak/mangooio#274] opened 2017-03-21 11:46 UTC
https://docs.mangoo.io/global-filter.html: method execute must return `Response`

```
public class MyGlobalFilter implements MangooRequestFilter {
    @Override
    public execute execute(Request request, Response response) {
        Locale.setDefault(Locale.ENGLISH);
        return response;
    }
}
```

https://docs.mangoo.io/creating-a-filter.html: there is not available anymore `MangooControllerFilter`
```
import io.mangoo.interfaces.MangooControllerFilter;

public class MyFilter implements MangooFilter {...}

```

**Comment by svenkubiak** [comment] 2017-03-21 12:10
Duplicate of #253 

Please add any update for the documentation to the above issue. Would be also great to directly comment at the specific page on docs.mangoo.io. Thanks ;-)

**Closed by svenkubiak** 2017-03-21 12:10 UTC

**Comment by ismagilov** [comment] 2017-03-21 12:19
Thanks for pointing! Didn't notice that it is possible to comment individual pages. But now I know, and I will comment, if I find something wrong.
