### ISSUE TITLE
template not reloading

### ISSUE THREAD

**Issue by ezcamlive** [svenkubiak/mangooio#114] opened 2016-01-06 13:44 UTC
I am running the app in dev mode and I see it on the console that it is infact dev mode.

However the changes to my freemarker templates are not reloaded when I change them.

**Comment by svenkubiak** [comment] 2016-01-07 11:13
Which version are you using? I just checked with an empty project from the archetype and template changes work finde.

**Comment by ezcamlive** [comment] 2016-01-07 11:38
I am using 2.1.0 but it was an old project upgraded to this version. I use sublime text for editing files.

**Comment by ezcamlive** [comment] 2016-01-07 12:32
I created a new project using 2.1.0 but seeing the same behavior.

If I refresh eclipse project after that I get this error.

Exception in thread "main" java.lang.NullPointerException
        at io.mangoo.core.Bootstrap.getModules(Bootstrap.java:314)
        at io.mangoo.core.Bootstrap.prepareInjector(Bootstrap.java:123)
        at io.mangoo.core.Application.main(Application.java:25)
07:30:40.568 [WaitForProcess-java.lang.ProcessImpl@261f511f] ERROR io.mangoo.bui
ld.Runner - JVM process terminated (next file change will attempt to restart it)

**Comment by ezcamlive** [comment] 2016-01-07 12:33
For template changes, why not just reload the template every time in dev mode instead of restarting the server?

**Comment by ezcamlive** [comment] 2016-01-07 12:36
Interestingly if I edit the file within eclipse, it works just fine.

**Comment by svenkubiak** [comment] 2016-01-07 14:28
Ok. I will have a deeper look at this asap.

**Comment by svenkubiak** [comment] 2016-01-10 06:47
Ok, just checked again and this is not a bug. When you start the app in dev mode via maven plugin, the file watchers listenes to every change in the /target folder, wether these are text, template, java classes, etc. Every change to a file, except temapltes, triggers a restart of the JVM.

However, you need some mechanism that recompiles and/or copies the files from the src folder to the target folder and this is done by your IDE of choice. If you change files in the source folder outside of an ide, these files are simply not compiles/copied to the target folder. Thus, template changes are not visible.

**Comment by ezcamlive** [comment] 2016-01-10 20:00
Thanks. I used a plugin for Sublime "FileSync" to do this and it works now.

I believe this is a maven thing but this is in contrast with play 1.0. Ideally I would like to see grunt livereload type of plugin in dev mode where I just need to change the source and don't even have to worry about syncing file system, compiling or even hitting refresh button between changes out of box. That will make this more productive than play 1.0.

**Comment by svenkubiak** [comment] 2016-01-11 07:58
Afaik play 1 did some magic by wrapping the reloading behind a python script. However, I will test if monitoring the sources works as good as monitoring the target folder. I'll close this is for now, okay?

**Closed by svenkubiak** 2016-01-11 07:58 UTC
Labels: no bug

**Comment by ezcamlive** [comment] 2016-01-11 11:41
ok. Thanks.
